// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMW0Jt38PRURvPDe2q8g3dynsGANBqMBY',
    appId: '1:527711758381:web:b21a854685a3f875b5b0a4',
    messagingSenderId: '527711758381',
    projectId: 'siti-maisarah-diary',
    authDomain: 'siti-maisarah-diary.firebaseapp.com',
    storageBucket: 'siti-maisarah-diary.firebasestorage.app',
    measurementId: 'G-22B0XVFR9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHFU7AIZu_vv_HeFH0s6aXANyfR2a1P0',
    appId: '1:527711758381:android:1cd0e0bf115ce27bb5b0a4',
    messagingSenderId: '527711758381',
    projectId: 'siti-maisarah-diary',
    storageBucket: 'siti-maisarah-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxM0RpKVRD8fNiA7Ak-bJg5ZpgrtP8URs',
    appId: '1:527711758381:ios:fe1ea2b36acef989b5b0a4',
    messagingSenderId: '527711758381',
    projectId: 'siti-maisarah-diary',
    storageBucket: 'siti-maisarah-diary.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMW0Jt38PRURvPDe2q8g3dynsGANBqMBY',
    appId: '1:527711758381:web:093e2a2757cd7847b5b0a4',
    messagingSenderId: '527711758381',
    projectId: 'siti-maisarah-diary',
    authDomain: 'siti-maisarah-diary.firebaseapp.com',
    storageBucket: 'siti-maisarah-diary.firebasestorage.app',
    measurementId: 'G-DB0GC1MCYG',
  );
}
